name: Auto-Update
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Repo
        run: |
          git config --global user.name "rexxu958"
          git config --global user.email "you@example.com"
          git add .
          git commit -m "Auto-Update"
          git push
